all : FirstStep SecondStep FourTwo

FirstStep : firststep.cpp Matrix.hpp
	clang++ -std=c++11 -o firststep firststep.cpp

SecondStep : secondstep.cpp Matrix.hpp Vector.hpp
	clang++ -std=c++11 -o secondstep secondstep.cpp

FourTwo : assignment4-2.hpp As4_2.cpp
	clang++ -std=c++11 -o As4_2 As4_2.cpp